<?php

/**
 * @file
 * Contains rw_people.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function rw_people_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the rw_people module.
    case 'help.page.rw_people':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provides content entity specifically more suited for capturing bpersonal information, like team members or organograms') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function rw_people_theme() {
  $theme = [];
  $theme['person'] = [
    'render element' => 'elements',
    'file' => 'person.page.inc',
    'template' => 'person',
  ];
  $theme['person_content_add_list'] = [
    'render element' => 'content',
    'variables' => ['content' => NULL],
    'file' => 'person.page.inc',
  ];
  return $theme;
}

/**
 * Implements hook_theme_suggestions_HOOK().
 */
function rw_people_theme_suggestions_person(array $variables) {
  $suggestions = [];
  $entity = $variables['elements']['#person'];
  $sanitized_view_mode = strtr($variables['elements']['#view_mode'], '.', '_');

  $suggestions[] = 'person__' . $sanitized_view_mode;
  $suggestions[] = 'person__' . $entity->bundle();
  $suggestions[] = 'person__' . $entity->bundle() . '__' . $sanitized_view_mode;
  $suggestions[] = 'person__' . $entity->id();
  $suggestions[] = 'person__' . $entity->id() . '__' . $sanitized_view_mode;
  return $suggestions;
}
